In [1]:
import  pandas as pd
import logging

In [2]:
# Path to data files
crash_data_file = "traffic_crashes.csv"
vehicle_crash_data_file = "traffic_crash_vehicle.csv"

In [3]:
# import data as DataFrame
df_crashes = pd.read_csv(f"data/{crash_data_file}")
df_vehicles = pd.read_csv(f"data/{vehicle_crash_data_file}")

In [4]:
#Stage: 1 Preliminary Task
# Crashes data
df_crashes.head()

,crash_record_id,rd_no,crash_date_est_i,crash_date,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,...,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,injuries_unknown,crash_hour,crash_day_of_week,crash_month,latitude,longitude,location
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,0.0,0.0,2.0,0.0,14,6,12,41.794850,-87.767280,POINT (-87.767280356289 41.794849958048)
1,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,0.0,0.0,2.0,0.0,14,6,12,41.881271,-87.686536,POINT (-87.686535940171 41.881270504288)
2,444221c2a9bc82fc4f301062ab22b482d7d661cf88fcdf...,JE494016,Y,2021-12-31T13:56:00.000,10,OTHER,NO CONTROLS,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.722941,-87.662863,POINT (-87.662862871273 41.72294121821)
3,4603435fbb4ef5d45c0d805c3e9aa5558a311a140a737e...,JE494049,NaN,2021-12-31T13:46:00.000,30,NO CONTROLS,NO CONTROLS,RAIN,DAYLIGHT,PEDALCYCLIST,...,1.0,0.0,2.0,0.0,13,6,12,41.766336,-87.578270,POINT (-87.578269718478 41.766335621716)
4,db62bb4534d0dae57112ea3ff8d50193784aaa732ed58d...,JE494000,NaN,2021-12-31T13:45:00.000,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,...,0.0,0.0,2.0,0.0,13,6,12,41.751150,-87.607802,POINT (-87.607802036151 41.7511501753)

In [5]:
df_crashes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 49 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   crash_record_id                1000 non-null   str
 1   rd_no                          1000 non-null   str
 2   crash_date_est_i               69 non-null     str
 3   crash_date                     1000 non-null   str
 4   posted_speed_limit             1000 non-null   int64
 5   traffic_control_device         1000 non-null   str
 6   device_condition               1000 non-null   str
 7   weather_condition              1000 non-null   str
 8   lighting_condition             1000 non-null   str
 9   first_crash_type               1000 non-null   str
 10  trafficway_type                1000 non-null   str
 11  lane_cnt                       1 non-null      float64
 12  alignment                      1000 non-null   str
 13  roadway_surface_cond           1000 non-null   str
 14  road_defect                    1000 non-null   str
 15  report_type                    976 non-null    str
 16  crash_type                     1000 non-null   str
 17  intersection_related_i         271 non-null    str
 18  private_property_i             45 non-null     str
 19  hit_and_run_i                  320 non-null    str
 20  damage                         1000 non-null   str
 21  date_police_notified           1000 non-null   str
 22  prim_contributory_cause        1000 non-null   str
 23  sec_contributory_cause         1000 non-null   str
 24  street_no                      1000 non-null   int64
 25  street_direction               1000 non-null   str
 26  street_name                    1000 non-null   str
 27  beat_of_occurrence             1000 non-null   int64
 28  photos_taken_i                 15 non-null     str
 29  statements_taken_i             22 non-null     str
 30  dooring_i                      0 non-null      float64
 31  work_zone_i                    4 non-null      str
 32  work_zone_type                 3 non-null      str
 33  workers_present_i              1 non-null      str
 34  num_units                      1000 non-null   int64
 35  most_severe_injury             998 non-null    str
 36  injuries_total                 998 non-null    float64
 37  injuries_fatal                 998 non-null    float64
 38  injuries_incapacitating        998 non-null    float64
 39  injuries_non_incapacitating    998 non-null    float64
 40  injuries_reported_not_evident  998 non-null    float64
 41  injuries_no_indication         998 non-null    float64
 42  injuries_unknown               998 non-null    float64
 43  crash_hour                     1000 non-null   int64
 44  crash_day_of_week              1000 non-null   int64
 45  crash_month                    1000 non-null   int64
 46  latitude                       987 non-null    float64
 47  longitude                      987 non-null    float64
 48  location                       987 non-null    str
dtypes: float64(11), int64(7), str(31)
memory usage: 829.2 KB

In [6]:

df_crashes.isnull().sum()

crash_record_id                     0
rd_no                               0
crash_date_est_i                  931
crash_date                          0
posted_speed_limit                  0
traffic_control_device              0
device_condition                    0
weather_condition                   0
lighting_condition                  0
first_crash_type                    0
trafficway_type                     0
lane_cnt                          999
alignment                           0
roadway_surface_cond                0
road_defect                         0
report_type                        24
crash_type                          0
intersection_related_i            729
private_property_i                955
hit_and_run_i                     680
damage                              0
date_police_notified                0
prim_contributory_cause             0
sec_contributory_cause              0
street_no                           0
street_direction                    0
street_name                         0
beat_of_occurrence                  0
photos_taken_i                    985
statements_taken_i                978
dooring_i                        1000
work_zone_i                       996
work_zone_type                    997
workers_present_i                 999
num_units                           0
most_severe_injury                  2
injuries_total                      2
injuries_fatal                      2
injuries_incapacitating             2
injuries_non_incapacitating         2
injuries_reported_not_evident       2
injuries_no_indication              2
injuries_unknown                    2
crash_hour                          0
crash_day_of_week                   0
crash_month                         0
latitude                           13
longitude                          13
location                           13
dtype: int64

In [7]:
df_crashes.dropna(axis='columns', how='all', inplace= True)

In [8]:
df_crashes = df_crashes.dropna(axis='index',thresh=2, inplace=False)

In [9]:
df_crashes['report_type'].unique()

<ArrowStringArray>
['ON SCENE', 'NOT ON SCENE (DESK REPORT)', nan]
Length: 3, dtype: str

In [10]:
df_crashes = df_crashes.fillna(value={'report_type': 'ON SCENE'})

In [11]:
# Vehicles DataFrame
df_vehicles.head()

,crash_unit_id,crash_record_id,rd_no,crash_date,unit_no,unit_type,num_passengers,vehicle_id,cmrc_veh_i,make,...,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class
0,1255349,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,1,DRIVER,NaN,1191605.0,NaN,DODGE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1255350,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,2,DRIVER,NaN,1191608.0,NaN,KIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1255351,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,2021-12-31T14:00:00.000,3,PARKED,NaN,1191614.0,NaN,CHRYSLER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1255367,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,2021-12-31T14:00:00.000,1,DRIVER,NaN,1191620.0,NaN,TOYOTA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1255368,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,2021-12-31T14:00:00.000,2,DRIVER,NaN,1191622.0,NaN,GENERAL MOTORS CORPORATION (GMC),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 72 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   crash_unit_id             1000 non-null   int64
 1   crash_record_id           1000 non-null   str
 2   rd_no                     1000 non-null   str
 3   crash_date                1000 non-null   str
 4   unit_no                   1000 non-null   int64
 5   unit_type                 999 non-null    str
 6   num_passengers            151 non-null    float64
 7   vehicle_id                981 non-null    float64
 8   cmrc_veh_i                16 non-null     str
 9   make                      981 non-null    str
 10  model                     981 non-null    str
 11  lic_plate_state           881 non-null    str
 12  vehicle_year              834 non-null    float64
 13  vehicle_defect            981 non-null    str
 14  vehicle_type              981 non-null    str
 15  vehicle_use               981 non-null    str
 16  travel_direction          981 non-null    str
 17  maneuver                  981 non-null    str
 18  towed_i                   195 non-null    str
 19  fire_i                    3 non-null      str
 20  occupant_cnt              981 non-null    float64
 21  exceed_speed_limit_i      0 non-null      float64
 22  towed_by                  150 non-null    str
 23  towed_to                  98 non-null     str
 24  area_00_i                 16 non-null     str
 25  area_01_i                 332 non-null    str
 26  area_02_i                 157 non-null    str
 27  area_03_i                 98 non-null     str
 28  area_04_i                 91 non-null     str
 29  area_05_i                 151 non-null    str
 30  area_06_i                 166 non-null    str
 31  area_07_i                 186 non-null    str
 32  area_08_i                 118 non-null    str
 33  area_09_i                 120 non-null    str
 34  area_10_i                 155 non-null    str
 35  area_11_i                 345 non-null    str
 36  area_12_i                 327 non-null    str
 37  area_99_i                 104 non-null    str
 38  first_contact_point       963 non-null    str
 39  cmv_id                    11 non-null     float64
 40  usdot_no                  6 non-null      float64
 41  ccmc_no                   1 non-null      float64
 42  ilcc_no                   1 non-null      float64
 43  commercial_src            6 non-null      str
 44  gvwr                      6 non-null      float64
 45  carrier_name              11 non-null     str
 46  carrier_state             11 non-null     str
 47  carrier_city              10 non-null     str
 48  hazmat_placards_i         1 non-null      str
 49  hazmat_name               0 non-null      float64
 50  un_no                     0 non-null      float64
 51  hazmat_present_i          7 non-null      str
 52  hazmat_report_i           7 non-null      str
 53  hazmat_report_no          0 non-null      float64
 54  mcs_report_i              7 non-null      str
 55  mcs_report_no             0 non-null      float64
 56  hazmat_vio_cause_crash_i  7 non-null      str
 57  mcs_vio_cause_crash_i     7 non-null      str
 58  idot_permit_no            1 non-null      float64
 59  wide_load_i               0 non-null      float64
 60  trailer1_width            0 non-null      float64
 61  trailer2_width            0 non-null      float64
 62  trailer1_length           0 non-null      float64
 63  trailer2_length           0 non-null      float64
 64  total_vehicle_length      0 non-null      float64
 65  axle_cnt                  0 non-null      float64
 66  vehicle_config            11 non-null     str
 67  cargo_body_type           10 non-null     str
 68  load_type                 8 non-null      str
 69  hazmat_out_of_service_i   6 non-null      str
 70  mcs_out_of_service_i      7 non-null      str
 71  hazmat_class              0 non-null      float64
dtypes: float64(23), int64(2), str(47)
memory usage: 800.2 KB

In [13]:
pd.set_option('display.max_rows', None)
df_vehicles.isnull().sum()

crash_unit_id                  0
crash_record_id                0
rd_no                          0
crash_date                     0
unit_no                        0
unit_type                      1
num_passengers               849
vehicle_id                    19
cmrc_veh_i                   984
make                          19
model                         19
lic_plate_state              119
vehicle_year                 166
vehicle_defect                19
vehicle_type                  19
vehicle_use                   19
travel_direction              19
maneuver                      19
towed_i                      805
fire_i                       997
occupant_cnt                  19
exceed_speed_limit_i        1000
towed_by                     850
towed_to                     902
area_00_i                    984
area_01_i                    668
area_02_i                    843
area_03_i                    902
area_04_i                    909
area_05_i                    849
area_06_i                    834
area_07_i                    814
area_08_i                    882
area_09_i                    880
area_10_i                    845
area_11_i                    655
area_12_i                    673
area_99_i                    896
first_contact_point           37
cmv_id                       989
usdot_no                     994
ccmc_no                      999
ilcc_no                      999
commercial_src               994
gvwr                         994
carrier_name                 989
carrier_state                989
carrier_city                 990
hazmat_placards_i            999
hazmat_name                 1000
un_no                       1000
hazmat_present_i             993
hazmat_report_i              993
hazmat_report_no            1000
mcs_report_i                 993
mcs_report_no               1000
hazmat_vio_cause_crash_i     993
mcs_vio_cause_crash_i        993
idot_permit_no               999
wide_load_i                 1000
trailer1_width              1000
trailer2_width              1000
trailer1_length             1000
trailer2_length             1000
total_vehicle_length        1000
axle_cnt                    1000
vehicle_config               989
cargo_body_type              990
load_type                    992
hazmat_out_of_service_i      994
mcs_out_of_service_i         993
hazmat_class                1000
dtype: int64

In [14]:
df_vehicles.dropna(axis='columns', how='all', inplace= True)

In [15]:
df_vehicles = df_vehicles.dropna(axis='index', thresh=2, inplace=False)

In [16]:
print(df_vehicles.shape)

(1000, 59)

In [17]:
cols_to_fill = [
    'unit_type',
    'vehicle_id',
    'make',
    'model',
    'vehicle_defect',
    'vehicle_type',
    'vehicle_use',
    'travel_direction',
    'maneuver',
    'occupant_cnt',
    'first_contact_point'
]

for col in cols_to_fill:
    print(f"\n{col}:")
    print(df_vehicles[col].unique())

unit_type:
<ArrowStringArray>
['DRIVER', 'PARKED', 'BICYCLE', 'PEDESTRIAN', 'DRIVERLESS', nan]
Length: 6, dtype: str

vehicle_id:
[1191605. 1191608. 1191614. 1191620. 1191622. 1191596. 1191600.      nan
 1191616. 1191602. 1191606. 1191619. 1191626. 1191638. 1191610. 1191621.
 1192147. 1192150. 1191597. 1191599. 1191578. 1191584. 1191741. 1191742.
 1192113. 1192119. 1191595. 1191601. 1192530. 1192535. 1191598. 1191603.
 1192982. 1192977. 1191564. 1191569. 1194606. 1191581. 1193644. 1193650.
 1191560. 1191566. 1191570. 1191575. 1191557. 1191567. 1191555. 1191558.
 1191568. 1191574. 1191590. 1191592. 1193331. 1193333. 1191577. 1191576.
 1191580. 1191529. 1191536. 1191563. 1191582. 1191588. 1191544. 1191551.
 1191545. 1191547. 1191528. 1191532. 1192096. 1192105. 1191685. 1191687.
 1192049. 1192053. 1192056. 1191713. 1191718. 1192055. 1192140. 1191542.
 1191546. 1191552. 1192419. 1192420. 1191941. 1191942. 1191946. 1191534.
 1191540. 1191977. 1191983. 1191990. 1192001. 1192009. 1199814. 1199815.
 1191515. 1191521. 1192589. 1192590. 1191510. 1191506. 1191516. 1191537.
 1191505. 1191520. 1191507. 1191511. 1192139. 1192145. 1191502. 1191504.
 1191508. 1192334. 1192337. 1191739. 1191737. 1191593. 1191594. 1191586.
 1191589. 1191483. 1191484. 1192913. 1192920. 1191591. 1191587. 1191481.
 1191479. 1191491. 1191500. 1191512. 1191485. 1191486. 1191489. 1191471.
 1191472. 1191475. 1191477. 1192040. 1192042. 1191738. 1191470. 1191469.
 1191465. 1191466. 1191462. 1191464. 1191455. 1191457. 1191454. 1191456.
 1191438. 1191439. 1191432. 1191435. 1191431. 1191434. 1191524. 1191526.
 1191531. 1191441. 1191428. 1191430. 1191443. 1191445. 1191426. 1191863.
 1191429. 1191433. 1191436. 1191421. 1191423. 1191437. 1191519. 1191523.
 1191417. 1191419. 1191420. 1191424. 1191416. 1191418. 1191410. 1191404.
 1191405. 1192499. 1192505. 1191413. 1191414. 1191407. 1191408. 1191427.
 1191425. 1191415. 1191422. 1191391. 1191397. 1191402. 1191390. 1191395.
 1191406. 1191409. 1191399. 1191403. 1191382. 1191388. 1191393. 1191440.
 1191442. 1191444. 1191492. 1191495. 1191396. 1191398. 1192580. 1191377.
 1191381. 1191384. 1191387. 1191389. 1191379. 1191380. 1191376. 1191394.
 1191400. 1191392. 1191401. 1191411. 1191412. 1191364. 1191371. 1191383.
 1191385. 1191530. 1191541. 1191369. 1191373. 1191368. 1191370. 1191351.
 1191355. 1191362. 1191365. 1191350. 1191354. 1191352. 1191358. 1192185.
 1192188. 1191346. 1191349. 1194783. 1194790. 1194798. 1193350. 1193315.
 1191360. 1191336. 1191340. 1191333. 1191338. 1191367. 1191372. 1191374.
 1191344. 1191345. 1191353. 1191357. 1191322. 1191325. 1191378. 1191386.
 1192465. 1192468. 1191319. 1191323. 1191306. 1191308. 1191299. 1192674.
 1192676. 1191327. 1191331. 1191332. 1191321. 1191337. 1191342. 1191329.
 1191335. 1191298. 1191304. 1191488. 1191487. 1191499. 1191501. 1191324.
 1191334. 1191307. 1191310. 1191539. 1191543. 1191305. 1191311. 1191348.
 1191302. 1191339. 1191276. 1191280. 1191271. 1191287. 1191291. 1191294.
 1191375. 1191256. 1191264. 1191309. 1191315. 1191467. 1191468. 1191318.
 1191326. 1191249. 1191252. 1191232. 1191236. 1191272. 1191275. 1191282.
 1191290. 1191296. 1191303. 1191263. 1191269. 1191259. 1191265. 1191313.
 1191316. 1191328. 1191260. 1191268. 1191285. 1191288. 1191247. 1191257.
 1191549. 1191550. 1191274. 1191278. 1191233. 1191239. 1191201. 1191273.
 1191277. 1191229. 1191237. 1191245. 1191187. 1191195. 1191216. 1191223.
 1195516. 1195517. 1191231. 1191240. 1191341. 1191356. 1191258. 1191261.
 1191267. 1191286. 1191235. 1191246. 1191209. 1191221. 1191196. 1191200.
 1191215. 1191218. 1191174. 1191177. 1191242. 1191251. 1191292. 1191293.
 1191243. 1191255. 1191213. 1191217. 1191228. 1191241. 1191175. 1191166.
 1191222. 1193011. 1193013. 1191168. 1191173. 1191179. 1191186. 1191191.
 1191194. 1191205. 1191211. 1193278. 1193283. 1191162. 1191169. 1191253.
 1191266. 1194038. 1194042. 1191176. 1191185. 1191156. 1191164. 1191190.
 1191202. 1191225. 1191227. 1191206. 1191219. 1191139. 1191140. 1191226.
 1191230. 1191132. 1191135. 1191188. 1191189. 1191143. 1191145. 1208645.
 1208646. 1191199. 1191210. 1191214. 1192912. 1192922. 1191155. 1191158.
 1191153. 1191133. 1191138. 1191197. 1191203. 1195015. 1195019. 1191122.
 1191116. 1191115. 1191120. 1191181. 1191184. 1191207. 1191192. 1191124.
 1191128. 1191141. 1191144. 1191474. 1191478. 1191101. 1191097. 1191112.
 1191113. 1191095. 1191098. 1191447. 1191449. 1191082. 1191074. 1191154.
 1191121. 1191125. 1191129. 1191111. 1191110. 1191109. 1191096. 1191102.
 1191114. 1191117. 1191094. 1191100. 1191099. 1191107. 1191076. 1191081.
 1191083. 1191090. 1191056. 1191062. 1191548. 1191553. 1191127. 1191066.
 1191060. 1191450. 1191451. 1191147. 1191150. 1191046. 1191053. 1191068.
 1191078. 1191088. 1191070. 1191079. 1191106. 1191067. 1191075. 1191165.
 1191171. 1192506. 1192509. 1191052. 1191059. 1191058. 1191064. 1191063.
 1191043. 1191048. 1191021. 1191027. 1191044. 1191054. 1191085. 1191089.
 1191013. 1191015. 1191244. 1191248. 1192562. 1192576. 1191000. 1191001.
 1190991. 1190995. 1191032. 1191039. 1191004. 1191028. 1191030. 1191002.
 1191006. 1191016. 1191012. 1191031. 1191480. 1191482. 1190986. 1190988.
 1191003. 1191008. 1191359. 1191361. 1190981. 1190982. 1190979. 1190977.
 1190985. 1190987. 1191446. 1191448. 1191198. 1191208. 1190980. 1190989.
 1190973. 1190975. 1191490. 1191497. 1190972. 1190968. 1190970. 1194252.
 1194254. 1190971. 1191363. 1191366. 1190967. 1190969. 1190992. 1190993.
 1190994. 1190997. 1190999. 1190958. 1190961. 1190964. 1190965. 1190966.
 1191513. 1191514. 1190952. 1190953. 1190954. 1190955. 1190960. 1191522.
 1191527. 1190959. 1190962. 1190949. 1190950. 1190951. 1190944. 1190945.
 1190938. 1190941. 1190939. 1190942. 1194334. 1194340. 1191055. 1191057.
 1191556. 1191559. 1190923. 1190927. 1190940. 1190943. 1190946. 1190931.
 1190936. 1190976. 1190922. 1190924. 1190932. 1190918. 1190937. 1190935.
 1190919. 1190920. 1190910. 1190915. 1190917. 1191533. 1191538. 1190947.
 1190948. 1190926. 1190929. 1190908. 1190909. 1190912. 1190913. 1190914.
 1190899. 1190902. 1190930. 1190934. 1191254. 1190900. 1190901. 1190903.
 1190907. 1191034. 1195046. 1195049. 1190895. 1191086. 1191091. 1190897.
 1190898. 1190889. 1190893. 1193213. 1190877. 1190871. 1190892. 1190894.
 1194077. 1194078. 1191509. 1191503. 1190916. 1190896. 1190872. 1190876.
 1190880. 1190883. 1190890. 1190891. 1190861. 1190863. 1190886. 1190885.
 1190928. 1190933. 1191072. 1191073. 1195218. 1195219. 1190870. 1190875.
 1190868. 1190874. 1192259. 1192274. 1190864. 1190867. 1190873. 1190879.
 1190881. 1191033. 1191037. 1191019. 1191025. 1190848. 1190860. 1190850.
 1190862. 1193923. 1193927. 1190845. 1190853. 1190834. 1190846. 1190839.
 1190854. 1190842. 1190882. 1191234. 1191238. 1190838. 1190843. 1190852.
 1190806. 1190811. 1190832. 1190835. 1190847. 1190855. 1190818. 1190821.
 1190831. 1190844. 1190921. 1190925. 1190816. 1190824. 1190837. 1190796.
 1190803. 1190807. 1190809. 1190808. 1190813. 1190823. 1190797. 1190802.
 1190800. 1190805. 1190792. 1190801. 1191118. 1191126. 1191007. 1191005.
 1190790. 1190794. 1190836. 1190841. 1190789. 1190825. 1190814. 1190840.
 1190851. 1193167. 1193168. 1190768. 1190777. 1191167. 1191193. 1194323.
 1194327. 1190781. 1190784. 1190812. 1190829. 1190859. 1190756. 1190767.
 1190773. 1190775. 1190760. 1190769. 1190778. 1194353. 1194355. 1192615.
 1192616. 1190754. 1190758. 1195173. 1195174. 1190782. 1190788. 1191137.
 1191142. 1190749. 1190752. 1190810. 1190820. 1190753. 1190764. 1190751.
 1190755. 1190763. 1190748. 1190750. 1190739. 1190744. 1190697. 1190704.
 1190865. 1190869. 1190774. 1190779. 1190693. 1190706. 1190776. 1190723.
 1190715. 1190702. 1190708. 1191170. 1191172. 1190725. 1190691. 1190990.
 1191022. 1190698. 1190700. 1190685. 1190672. 1190759. 1190766. 1191036.
 1191460. 1190677. 1190682. 1190684. 1190679. 1190686. 1190712. 1190714.
 1198367. 1198371. 1190722. 1190730. 1190661. 1190669. 1190647. 1190652.
 1190650. 1190692. 1190690. 1190707. 1190719. 1190724. 1190671. 1190676.
 1190683. 1190689. 1190711. 1190732. 1190629. 1190635. 1190675. 1190678.
 1190757. 1190770. 1190696. 1190709. 1190642. 1190662. 1190996. 1190998.
 1190729. 1190734. 1190670. 1190673. 1190651. 1190659. 1190665. 1191494.
 1191498. 1190658. 1190663. 1190617. 1190632. 1190974. 1190978. 1190737.
 1190741. 1190620. 1190628. 1190613. 1191041. 1191042. 1190587. 1190593.
 1190637. 1190657. 1190595. 1190599. 1194903. 1194908. 1190586. 1190588.
 1190589. 1190591. 1190640. 1190884. 1190603. 1190611. 1190627. 1190601.
 1190612. 1190619. 1190695. 1190703. 1190713. 1190716. 1190569. 1190571.
 1190584. 1190590. 1190621. 1190625. 1190610. 1190567. 1190568. 1192137.
 1192138. 1191131. 1191136. 1190553. 1190558. 1190643. 1190648. 1190655.
 1190572. 1190579. 1190580. 1190582. 1190563. 1190574. 1190576. 1190581.
 1190549. 1190555. 1190533. 1190541. 1190524. 1190537. 1190522. 1190526.
 1190856. 1190858. 1190552. 1190556. 1190559. 1190532. 1190539. 1191561.
 1191562. 1191493. 1191496. 1190564. 1190575. 1190634. 1190641. 1190638.
 1190626. 1190674. 1190680. 1190540. 1190550. 1190519.]

make:
<ArrowStringArray>
[                                              'DODGE',
                                                 'KIA',
                                            'CHRYSLER',
                                              'TOYOTA',
                    'GENERAL MOTORS CORPORATION (GMC)',
                                           'CHEVROLET',
                                                   nan,
                                                'FORD',
                                             'UNKNOWN',
                                             'LINCOLN',
                                          'MITSUBISHI',
                                              'SUBARU',
                                                'JEEP',
                                             'HYUNDAI',
                                               'SCION',
                                       'MERCEDES-BENZ',
                                              'NISSAN',
                                              'HUMMER',
                                               'HONDA',
                                              'SUZUKI',
                                               'MAZDA',
                                                 'BMW',
                                              'SATURN',
                                               'ACURA',
                                               'LEXUS',
                                             'PONTIAC',
                                          'VOLKSWAGEN',
                            'FREIGHTLINER CORPORATION',
                                             'MERCURY',
                                               'BUICK',
                                            'INFINITI',
                                            'CADILLAC',
                                                'SAAB',
                                                'AUDI',
                                            'NOVA BUS',
                               'FLEETWOOD ENTERPRISES',
                               'SUBURBAN MOTORS, INC.',
                   'INTERNATIONAL TRAILER CORPORATION',
                                                'MINI',
                                               'TESLA',
                                               'ISUZU',
    'CASE, J.I. COMPANY (SUBSIDIARY OF TENNECO, INC.)',
                                               'VOLVO',
                                              'JAGUAR',
             'ASSICUATED TRUCK & TRAILER (TIGARD, OR)',
                                           'NEW FLYER',
                              'BLUEBIRD INTERNATIONAL',
                                   'MACK TRUCKS, INC.',
                                            'DART, KW',
                                          'LAND ROVER',
                                                'HINO',
 'PETERBILT MOTORS COMPANY (DIVISION OF PACCAR, INC.)']
Length: 52, dtype: str

model:
<ArrowStringArray>
[                                    'CHARGER',
                                      'SEDONA',
                                    'PACIFICA',
                                      'TUNDRA',
                                       'ENVOY',
                'OTHER (EXPLAIN IN NARRATIVE)',
                                        'TRAX',
                                           nan,
                                    'EXPLORER',
                                     'COROLLA',
 ...
                                     'LUCERNE',
                                      'GLK350',
                                         'SRX',
                                    'DART, KW',
                                    'DEFENDER',
                                        'F450',
                                       'PRIZM',
                                  '250 SERIES',
                                        'HINO',
 'PETERBILT MOTORS CO., DIVISION PACCAR, INC.']
Length: 241, dtype: str

vehicle_defect:
<ArrowStringArray>
['UNKNOWN', 'NONE', nan, 'OTHER', 'ENGINE/MOTOR', 'BRAKES', 'LIGHTS']
Length: 7, dtype: str

vehicle_type:
<ArrowStringArray>
[                    'UNKNOWN/NA',                   'VAN/MINI-VAN',
                         'PICKUP',    'SPORT UTILITY VEHICLE (SUV)',
                      'PASSENGER',                              nan,
                          'OTHER',            'TRUCK - SINGLE UNIT',
     'MOPED OR MOTORIZED BICYCLE',              'BUS OVER 15 PASS.',
 'SINGLE UNIT TRUCK WITH TRAILER',       'TRACTOR W/O SEMI-TRAILER',
        'TRACTOR W/ SEMI-TRAILER',     'OTHER VEHICLE WITH TRAILER']
Length: 14, dtype: str

vehicle_use:
<ArrowStringArray>
[              'UNKNOWN/NA',                 'PERSONAL',
                        nan,                   'POLICE',
                'TOW TRUCK',               'NOT IN USE',
                    'OTHER',        'RIDESHARE SERVICE',
            'TAXI/FOR HIRE',                     'FIRE',
  'COMMERCIAL - MULTI-UNIT', 'CONSTRUCTION/MAINTENANCE',
 'COMMERCIAL - SINGLE UNIT',                'AMBULANCE',
                      'CTA',              'STATE OWNED',
               'SCHOOL BUS']
Length: 17, dtype: str

travel_direction:
<ArrowStringArray>
['W', 'N', 'E', nan, 'SE', 'NW', 'UNKNOWN', 'S', 'SW', 'NE']
Length: 10, dtype: str

maneuver:
<ArrowStringArray>
[                      'TURNING LEFT',                     'STRAIGHT AHEAD',
                             'PARKED',                             'U-TURN',
                                  nan,                     'CHANGING LANES',
               'SLOW/STOP IN TRAFFIC',                         'UNKNOWN/NA',
 'ENTERING TRAFFIC LANE FROM PARKING',                            'BACKING',
                      'TURNING RIGHT',                              'OTHER',
                 'PASSING/OVERTAKING',       'LEAVING TRAFFIC LANE TO PARK',
                  'DRIVING WRONG WAY',                            'MERGING',
             'ENTER FROM DRIVE/ALLEY',          'AVOIDING VEHICLES/OBJECTS',
                'STARTING IN TRAFFIC',             'PARKED IN TRAFFIC LANE',
              'SKIDDING/CONTROL LOSS',                         'DRIVERLESS']
Length: 22, dtype: str

occupant_cnt:
[ 1.  0. nan  2.  3.  4.  6.  5.  7.]

first_contact_point:
<ArrowStringArray>
[            'OTHER',           'UNKNOWN',              'ROOF',
 'TOTAL (ALL AREAS)',        'SIDE-RIGHT',                 nan,
             'FRONT',              'REAR',         'REAR-LEFT',
        'REAR-RIGHT',         'SIDE-LEFT',    'UNDER CARRIAGE',
        'FRONT-LEFT',       'FRONT-RIGHT',              'NONE']
Length: 15, dtype: str

In [18]:
df_vehicles = df_vehicles.fillna(value={
    'unit_type': 'DRIVER',
    'make': 'UNKNOWN',
    'model': 'OTHER (EXPLAIN IN NARRATIVE)',
    'vehicle_defect': 'UNKNOWN',
    'vehicle_type': 'UNKNOWN/NA',
    'vehicle_use': 'UNKNOWN/NA',
    'travel_direction': 'UNKNOWN',
    'maneuver': 'UNKNOWN/NA',
    'occupant_cnt': 0,
    'first_contact_point': 'UNKNOWN'
})

In [19]:
pd.set_option('display.max_rows', None)
df_vehicles.isnull().sum()

crash_unit_id                 0
crash_record_id               0
rd_no                         0
crash_date                    0
unit_no                       0
unit_type                     0
num_passengers              849
vehicle_id                   19
cmrc_veh_i                  984
make                          0
model                         0
lic_plate_state             119
vehicle_year                166
vehicle_defect                0
vehicle_type                  0
vehicle_use                   0
travel_direction              0
maneuver                      0
towed_i                     805
fire_i                      997
occupant_cnt                  0
towed_by                    850
towed_to                    902
area_00_i                   984
area_01_i                   668
area_02_i                   843
area_03_i                   902
area_04_i                   909
area_05_i                   849
area_06_i                   834
area_07_i                   814
area_08_i                   882
area_09_i                   880
area_10_i                   845
area_11_i                   655
area_12_i                   673
area_99_i                   896
first_contact_point           0
cmv_id                      989
usdot_no                    994
ccmc_no                     999
ilcc_no                     999
commercial_src              994
gvwr                        994
carrier_name                989
carrier_state               989
carrier_city                990
hazmat_placards_i           999
hazmat_present_i            993
hazmat_report_i             993
mcs_report_i                993
hazmat_vio_cause_crash_i    993
mcs_vio_cause_crash_i       993
idot_permit_no              999
vehicle_config              989
cargo_body_type             990
load_type                   992
hazmat_out_of_service_i     994
mcs_out_of_service_i        993
dtype: int64

In [20]:
df = df_crashes.merge(df_vehicles, how='left', on='crash_record_id',suffixes=('_left','_right'))

In [21]:
print(df.shape)

(1510, 106)

In [22]:
df.head()

,crash_record_id,rd_no_left,crash_date_est_i,crash_date_left,posted_speed_limit,traffic_control_device,device_condition,weather_condition,lighting_condition,first_crash_type,...,hazmat_report_i,mcs_report_i,hazmat_vio_cause_crash_i,mcs_vio_cause_crash_i,idot_permit_no,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i
0,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,530411c8611eb0ccb9b25f16b2955cd21761fa1928dcaa...,JE494048,NaN,2021-12-31T14:00:00.000,35,NO CONTROLS,NO CONTROLS,CLEAR,DAYLIGHT,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,305b06235b250aa0029c07313c84f969f4bc13c1cc3715...,JE494008,NaN,2021-12-31T14:00:00.000,30,TRAFFIC SIGNAL,UNKNOWN,CLEAR,DUSK,TURNING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_agg = df.groupby('vehicle_type').agg({'crash_record_id': 'count'}).reset_index()

In [24]:
df_agg.head()

                 vehicle_type  crash_record_id
0           BUS OVER 15 PASS.                5
1  MOPED OR MOTORIZED BICYCLE                1
2                       OTHER               20
3  OTHER VEHICLE WITH TRAILER                1
4                   PASSENGER              633

In [25]:
number_of_passenger_cars_involved = df_agg[df_agg['vehicle_type']== 'PASSENGER']['crash_record_id'].array[0]

In [26]:
number_of_passenger_cars_involved

np.int64(633)

In [27]:
vehicle_mapping = {'vehicle_type':'vehicletypes'}

In [28]:
df_agg = df_agg.rename(columns=vehicle_mapping)

In [29]:
df_agg

                      vehicletypes  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA              108
12                    VAN/MINI-VAN               38

In [30]:
# stage 2

In [31]:
def get_transformed_data(crash_file,vehicle_file):
    # import data

    df_crashes = pd.read_csv(f"data/{crash_file}")
    df_vehicles = pd.read_csv(f"data/{vehicle_file}")

    # crashes
    df_crashes.dropna(axis='columns', how='all', inplace= True)
    under_threshold_removed = df_crashes.dropna(axis='index', thresh=2, inplace=False)
    under_threshold_rows = df_crashes[~df_crashes.index.isin(under_threshold_removed.index)]
    df_crashes.fillna(value={'report_type': 'ON SCENE'},inplace=True)

    # vehicles
    df_vehicles.dropna(axis='columns', how='all', inplace= True)
    under_threshold_removed = df_vehicles.dropna(axis= 'index', thresh=2, inplace= False)
    under_threshold_rows = df_vehicles[~df_vehicles.index.isin(under_threshold_removed.index)]
    df_vehicles = df_vehicles.fillna(value={
        'unit_type': 'DRIVER',
        'make': 'UNKNOWN',
        'model': 'OTHER (EXPLAIN IN NARRATIVE)',
        'vehicle_defect': 'UNKNOWN',
        'vehicle_type': 'UNKNOWN/NA',
        'vehicle_use': 'UNKNOWN/NA',
        'travel_direction': 'UNKNOWN',
        'maneuver': 'UNKNOWN/NA',
        'occupant_cnt': 0,
        'first_contact_point': 'UNKNOWN'
    })

    # Merge crashes and vehicle

    df = df_crashes.merge(df_vehicles, how='left', on='crash_record_id', suffixes=('_left','_right'))
    df_agg = df.groupby('vehicle_type').agg({'crash_record_id': 'count'}).reset_index()

    vehicle_mapping = {'vehicle_type': 'vehicletypes'}
    df_agg = df_agg.rename(columns=vehicle_mapping)
    return df_agg

results = get_transformed_data(crash_data_file,vehicle_crash_data_file)
print(results)

                      vehicletypes  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA              108
12                    VAN/MINI-VAN               38

In [32]:
# stage 3
def read_data_source(source_name):
    df = pd.read_csv(f"data/{source_name}")
    return df

In [33]:
def drop_columns_with_null_values(df):
    df = df.dropna(axis='columns', how='all', inplace= True)
    return df

In [34]:
def drop_rows_with_null_values(df):
    under_threshold_removed = df.dropna(axis='index', thresh=2, inplace= False)
    df = df[~df.index.isin(under_threshold_removed.index)]
    return df

In [35]:
def fill_missing_crash_values(df):
    df = df.fillna(value={'report_type': 'ON SCENE'})
    return df

In [36]:
def fill_missing_vehicle_values(df):
        df = df.fillna(value={
        'unit_type': 'DRIVER',
        'make': 'UNKNOWN',
        'model': 'OTHER (EXPLAIN IN NARRATIVE)',
        'vehicle_defect': 'UNKNOWN',
        'vehicle_type': 'UNKNOWN/NA',
        'vehicle_use': 'UNKNOWN/NA',
        'travel_direction': 'UNKNOWN',
        'maneuver': 'UNKNOWN/NA',
        'occupant_cnt': 0,
        'first_contact_point': 'UNKNOWN'
    })
        return df

In [56]:
def merge_dataframes(df_crashes,df_vehicles):
    df = df_crashes.merge(df_vehicles, how='left', on='crash_record_id', suffixes=('_left','_right'))
    df_agg = df.groupby('vehicle_type').agg({'crash_record_id': 'count'}).reset_index()
    return df_agg

df_agg = merge_dataframes(df_crashes, df_vehicles)
print(df_agg)

                      vehicle_type  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA              108
12                    VAN/MINI-VAN               38

In [57]:
def rename_columns(df_agg):
    vehicle_mapping = {'vehicle_type':'vehicletypes'}
    df = df_agg.rename(columns=vehicle_mapping)
    return df

df_output = rename_columns(df_agg)
print(df_output)

                      vehicletypes  crash_record_id
0                BUS OVER 15 PASS.                5
1       MOPED OR MOTORIZED BICYCLE                1
2                            OTHER               20
3       OTHER VEHICLE WITH TRAILER                1
4                        PASSENGER              633
5                           PICKUP               33
6   SINGLE UNIT TRUCK WITH TRAILER                2
7      SPORT UTILITY VEHICLE (SUV)              138
8          TRACTOR W/ SEMI-TRAILER                5
9         TRACTOR W/O SEMI-TRAILER                2
10             TRUCK - SINGLE UNIT               14
11                      UNKNOWN/NA              108
12                    VAN/MINI-VAN               38